### ISSUE TITLE
Upgrade to 3.3.5

### ISSUE THREAD

**Issue by djenniex** [englue/meteor-bootstrap3-sass#26]
Any chance of upgrading the current version of Bootstrap to 3.3.5? I'm having issues with the breadcrumbs not displaying properly, which is fixed in https://github.com/twbs/bootstrap-sass/issues/919

**Comment by derwaldgeist** [comment]
Bump.

I'm also having problems with buttons nested in toolbars, which is fixed in 3.3.5

**Comment by reywood** [comment]
Done. Sorry for the delay.

**Comment by gowlin** [comment]
@djenniex  did this fix the breadcrumb issue for you?  I'm still having that problem.

**Comment by djenniex** [comment]
@gowlin Yes, it did fix the breadcrumb issues. Everything is good now.
